import { test, expect } from "@playwright/test";
// Real voice flow on the preview (8082) with a spoken sentence fed into Chrome's fake microphone.
const WAV = "/private/tmp/claude-501/-Volumes-Macintosh-HD---Data-NetworQ-main/8ca26726-2240-4ffb-9927-8bf08a5a0a39/scratchpad/speech.wav";
test.use({ launchOptions: { args: ["--use-fake-ui-for-media-stream", "--use-fake-device-for-media-stream", `--use-file-for-fake-audio-capture=${WAV}`] } });
test("voice note: speak → transcribe → details → save", async ({ browser }) => {
  test.setTimeout(240_000);
  const ctx = await browser.newContext({ permissions: ["microphone"] });
  const page = await ctx.newPage();
  const errors: string[] = [];
  page.on("pageerror", (e) => errors.push(e.message));
  page.on("console", (m) => m.text().includes("[voice]") && console.log(m.text()));
  await page.setViewportSize({ width: 393, height: 852 });
  await page.goto("http://localhost:8082/?devLogin=a");
  await expect(page.getByRole("navigation", { name: "Main navigation" })).toBeVisible({ timeout: 120_000 });
  await page.getByRole("button", { name: "Voice note", exact: true }).click();
  const sheet = page.getByRole("dialog", { name: "Voice note" });
  await sheet.getByRole("button", { name: "Start recording" }).click();
  await expect(sheet.getByRole("status")).toHaveText(/Listening… \d:\d\d/, { timeout: 10_000 });
  await page.waitForTimeout(2500);
  await page.screenshot({ path: "qa-logs/voice-1-listening.png" });
  await page.waitForTimeout(6000);
  await sheet.getByRole("button", { name: "Stop recording" }).click();
  await expect(sheet.getByRole("status")).toHaveText(/Writing it down…|Got it/, { timeout: 10_000 });
  const box = sheet.getByRole("textbox");
  await expect(box).toHaveValue(/Priya/i, { timeout: 45_000 });
  console.log("TRANSCRIPT:", await box.inputValue());
  await page.screenshot({ path: "qa-logs/voice-2-transcript.png" });
  await sheet.getByRole("button", { name: "Continue" }).click();
  await expect(page.getByRole("dialog", { name: "Voice note" }).getByText("Check the details")).toBeVisible({ timeout: 45_000 });
  const name = sheet.getByLabel("Name");
  console.log("NAME:", await name.inputValue(), "| COMPANY:", await sheet.getByLabel("Company").inputValue(), "| NEXT:", await sheet.getByLabel("Next step").inputValue());
  console.log("REMIND:", await sheet.getByRole("radio", { checked: true }).innerText());
  await page.screenshot({ path: "qa-logs/voice-3-review.png", fullPage: false });
  expect(await name.inputValue()).toMatch(/Priya/i);
  await sheet.getByRole("button", { name: "Save contact" }).click();
  await expect(sheet.getByText(/is saved$/)).toBeVisible({ timeout: 20_000 });
  await page.screenshot({ path: "qa-logs/voice-4-saved.png" });
  await sheet.getByRole("button", { name: "Done" }).click();
  await expect(page.getByRole("button", { name: /^Open Priya/ }).first()).toBeVisible({ timeout: 15_000 });
  console.log("errors:", JSON.stringify(errors));
});
